version: '3'
services:
  mongo_db:
    image: mongo
    container_name: ${MONGO_CONTAINER_NAME}
    volumes:
      - '${MONGO_DATA_PATH}/db:/data/db'
      - '${MONGO_DATA_PATH}/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro'
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}

  mongo_express:
    image: mongo-express
    container_name: ${MONGO_EXPRESS_CONTAINER_NAME}
    depends_on:
      - mongo_db
    # ports:
    #   - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: ${MONGO_CONTAINER_NAME}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      VIRTUAL_PORT: ${VIRTUAL_PORT}
      LETSENCRYPT_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL} 

networks:
  default:
    external:
      name: ${NETWORK}
